apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-internal        # ingress-nginx 컨트롤러 내부 접근용 Service
  namespace: edge                     # edge 네임스페이스에 생성
spec:
  type: ClusterIP                     # 클러스터 내부에서만 접근 가능한 가상 IP (외부 노출 X)
  selector:
    app: ingress-nginx                # app=ingress-nginx 라벨을 가진 Pod(컨트롤러)로 트래픽 전달
  ports:
    - name: metrics                   # 포트 이름 (targetPort 매칭에 사용)
      port: 10254                     # Service가 노출하는 포트(클러스터 내부에서 접근할 포트)
      targetPort: metrics             # 컨테이너의 ports.name=metrics(=10254)로 라우팅
