# ===============================
# infra 네임스페이스 정의
# ===============================
# → DB, Redis, MQ 등 인프라 워크로드 전용 공간
# → 일반 APP/EDGE와 명확히 분리하여 보안 경계 형성
apiVersion: v1
kind: Namespace
metadata:
  # 인프라 전용 네임스페이스 이름
  name: infra

  labels:
    # 네임스페이스 식별 및 정책(NetworkPolicy/모니터링)용 라벨
    name: infra
---
# ===============================
# Jenkins 배포용 Role (infra 한정)
# ===============================
# → Jenkins가 infra 네임스페이스의 인프라 워크로드만
#    배포/관리할 수 있도록 최소 권한 부여
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  # Role 이름
  # → edge / app 과 동일한 이름 사용 가능 (네임스페이스 분리)
  name: jenkins-deployer

  # 이 Role이 적용되는 네임스페이스
  # → infra 네임스페이스 리소스만 제어 가능
  namespace: infra

rules:
  # ===============================
  # 1️⃣ 인프라 워크로드 관리
  # ===============================
  - apiGroups: ["apps"]              # apps API 그룹
    resources:
      - deployments                  # Redis, exporter 등 stateless infra
      - statefulsets                 # DB, MQ 등 상태 저장 infra
    verbs:
      - get                          # 조회
      - list                         # 목록 조회
      - watch                        # 변경 감시 (rollout 상태 확인)
      - create                       # 신규 배포
      - update                       # 전체 수정
      - patch                        # 부분 수정 (helm upgrade 필수)
      - delete                       # 워크로드 제거

  # ===============================
  # 2️⃣ Service / ConfigMap 관리
  # ===============================
  - apiGroups: [""]                  # core API 그룹
    resources:
      - services                     # 내부 통신용 Service
      - configmaps                   # 설정 값 (비밀 제외)
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ===============================
  # 3️⃣ 네트워크 정책 관리
  # ===============================
  # → infra 네임스페이스 접근 경로를 엄격히 통제
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies              # Pod 간 통신 제어
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ===============================
  # 4️⃣ 상태 확인 / 디버깅 전용
  # ===============================
  # → 장애 원인 파악은 가능하지만
  #    리소스 파괴/변조는 불가능
  - apiGroups: [""]                  # core API 그룹
    resources:
      - pods                         # Pod 상태 확인
      - events                       # 오류/경고 이벤트 확인
    verbs:
      - get
      - list
      - watch                        # ⚠️ 읽기 전용
---
# ===============================
# RoleBinding: Jenkins ↔ infra Role 연결
# ===============================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  # RoleBinding 이름
  name: jenkins-deployer

  # infra 네임스페이스에서만 권한 유효
  namespace: infra

subjects:
  # 권한을 부여받을 대상
  - kind: ServiceAccount             # Kubernetes 서비스 계정
    name: jenkins                    # Jenkins가 사용하는 SA
    namespace: cicd                  # Jenkins가 실행 중인 네임스페이스

roleRef:
  # 참조할 Role 정의
  apiGroup: rbac.authorization.k8s.io
  kind: Role                         # ClusterRole 아님 → namespace 한정
  name: jenkins-deployer             # 위에서 정의한 Role
