# ===============================
# Namespace 정의
# ===============================
apiVersion: v1
kind: Namespace
metadata:
  # 애플리케이션 전용 네임스페이스
  # → SCG 뒤에서 실제 서비스(APP Pod)들이 배포되는 공간
  name: app

  labels:
    # 네임스페이스 식별용 라벨
    # → 모니터링, 정책(NetworkPolicy), 관리 목적
    name: app
---
# ===============================
# Jenkins 배포용 Role (app 네임스페이스 한정)
# ===============================
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  # Role 이름
  # → Jenkins가 app 네임스페이스에 배포할 때 사용하는 권한 묶음
  name: jenkins-deployer

  # 이 Role이 적용되는 네임스페이스
  # → Jenkins는 app 네임스페이스 리소스만 제어 가능
  namespace: app

rules:
  # ===============================
  # 1️⃣ 애플리케이션 워크로드 관리 권한
  # ===============================
  - apiGroups: ["apps"]              # apps API 그룹
    resources:
      - deployments                  # 일반 APP 배포 (stateless)
      - statefulsets                 # 상태 기반 APP (필요 시)
      - replicasets                  # Deployment 하위 리소스
    verbs:
      - get                          # 조회
      - list                         # 목록 조회
      - watch                        # 변경 감시 (rollout 상태 확인)
      - create                       # 신규 배포
      - update                       # 전체 수정
      - patch                        # 부분 수정 (helm upgrade 필수)
      - delete                       # 배포 제거

  # ===============================
  # 2️⃣ Service / ConfigMap 관리
  # ===============================
  - apiGroups: [""]                  # core API 그룹
    resources:
      - services                     # ClusterIP / NodePort
      - configmaps                   # 환경 설정 (비밀 제외)
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ===============================
  # 3️⃣ Ingress / 네트워크 정책
  # ===============================
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses                    # 외부 트래픽 진입점
      - networkpolicies              # Pod 간 통신 제어
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ===============================
  # 4️⃣ 상태 확인 / 디버깅 전용
  # ===============================
  - apiGroups: [""]                  # core API 그룹
    resources:
      - pods                         # Pod 상태 확인
      - events                       # 배포 오류 / 경고 이벤트
    verbs:
      - get
      - list
      - watch                        # ⚠️ 생성/삭제 불가 (조회 전용)
---
# ===============================
# RoleBinding: Jenkins ↔ Role 연결
# ===============================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  # RoleBinding 이름
  name: jenkins-deployer

  # RoleBinding이 적용되는 네임스페이스
  # → app 네임스페이스에서만 권한 유효
  namespace: app

subjects:
  # 권한을 부여받을 대상
  - kind: ServiceAccount             # Kubernetes 서비스 계정
    name: jenkins                    # Jenkins가 사용하는 SA
    namespace: cicd                  # Jenkins가 실행 중인 네임스페이스

roleRef:
  # 참조할 권한 정의
  apiGroup: rbac.authorization.k8s.io
  kind: Role                         # ClusterRole 아님 → namespace 한정
  name: jenkins-deployer             # 위에서 정의한 Role
